#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Jan 05, 2020 02:58:53 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import login_page_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    login_page_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    login_page_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family {Yu Gothic Medium} -size 21 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI} -size 11 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family Arial -size 20 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("895x685+503+126")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(background="#a0efe7")
        self.Frame1.configure(highlightbackground="#a0efe7")
        self.Frame1.configure(width=895)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.268, rely=0.058, height=56, width=482)
        self.Label1.configure(background="#66d869")
        self.Label1.configure(borderwidth="10")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#a0efe7")
        self.Label1.configure(relief='raised')
        self.Label1.configure(text='''Attendence Login System''')
        self.Label1.configure(width=482)

        self.Labelframe1 = tk.LabelFrame(self.Frame1)
        self.Labelframe1.place(relx=0.246, rely=0.263, relheight=0.255
                , relwidth=0.57)
        self.Labelframe1.configure(relief='raised')
        self.Labelframe1.configure(borderwidth="10")
        self.Labelframe1.configure(font=font12)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(relief='raised')
        self.Labelframe1.configure(background="#66d869")
        self.Labelframe1.configure(highlightbackground="#a0efe7")
        self.Labelframe1.configure(highlightthickness="20")
        self.Labelframe1.configure(width=510)

        self.Label2 = tk.Label(self.Labelframe1)
        self.Label2.place(relx=0.098, rely=0.229, height=31, width=121
                , bordermode='ignore')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font11)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Username''')
        self.Label2.configure(width=121)

        self.Entry1 = tk.Entry(self.Labelframe1)
        self.Entry1.place(relx=0.382, rely=0.229, height=34, relwidth=0.4
                , bordermode='ignore')
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=204)

        self.Label3 = tk.Label(self.Labelframe1)
        self.Label3.place(relx=0.098, rely=0.486, height=31, width=116
                , bordermode='ignore')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font11)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Password''')
        self.Label3.configure(width=116)

        self.Frame2 = tk.Frame(self.Labelframe1)
        self.Frame2.place(relx=-0.51, rely=0.4, relheight=0.429, relwidth=0.245
                , bordermode='ignore')
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(width=125)

        self.Entry2 = tk.Entry(self.Labelframe1)
        self.Entry2.place(relx=0.382, rely=0.486, height=34, relwidth=0.4
                , bordermode='ignore')
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(width=204)

        self.Labelframe2 = tk.LabelFrame(self.Frame1)
        self.Labelframe2.place(relx=0.257, rely=0.526, relheight=0.124
                , relwidth=0.547)
        self.Labelframe2.configure(relief='ridge')
        self.Labelframe2.configure(borderwidth="10")
        self.Labelframe2.configure(font=font12)
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(relief='ridge')
        self.Labelframe2.configure(background="#8ad8d0")
        self.Labelframe2.configure(highlightbackground="#8defe8")
        self.Labelframe2.configure(highlightcolor="#3f635e")
        self.Labelframe2.configure(highlightthickness="22")
        self.Labelframe2.configure(width=490)

        self.Button1 = tk.Button(self.Labelframe2)
        self.Button1.place(relx=0.061, rely=0.235, height=33, width=146
                , bordermode='ignore')
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#8cd86c")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Button''')
        self.Button1.configure(width=146)

        self.Button2 = tk.Button(self.Labelframe2)
        self.Button2.place(relx=0.357, rely=0.235, height=33, width=146
                , bordermode='ignore')
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#8cd86c")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Button''')
        self.Button2.configure(width=146)

        self.Button3 = tk.Button(self.Labelframe2)
        self.Button3.place(relx=0.653, rely=0.235, height=33, width=136
                , bordermode='ignore')
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#8cd86c")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Button''')
        self.Button3.configure(width=136)

if __name__ == '__main__':
    vp_start_gui()





